### PR TITLE
Simplify register command function

### PR DESCRIPTION
**Pull request by pizzafox**
Simplify register command function.

### CODE REVIEW

**Comment by chroventer** [comment]
@bananaprotocol, please either close or merge this pull request.

**Comment by bananaprotocol** [comment]
Hey @pizzafox, thanks for your contribution!
I'll take a look at this pull request, and let you know what I think about it.

**Comment by chroventer** [comment]
@bananaprotocol Check out this [pull request (custom server prefix)](https://github.com/bananaprotocol/confax/pull/35)

**Comment by bananaprotocol** [comment]
Merged, thank you!

**Pull request closed without merging**
