### PR TITLE
Add option to 'react' to a post to initiate the code formatting.

### PR DESCRIPTION
**Pull request by GlassToeStudio**

### CODE REVIEW

**Comment by GlassToeStudio** [comment]
I made a change to the CheckForCode module. Add option to 'react' to a post to initiate the code formatting. Made a bool in config.json "autoPost" that, if false, the un-formatted code is detected and an emoji is added to the post. If this emoji is pressed, the new formatted message will be posted. This will of course have to be pressed manually, so no more auto posting of the code. But should fix the issue of unintended re-posting.

**Comment by tomzig16** [comment]
I think adding a message to tell user "Hey click this emoji to auto format your code" could help a lot, especially as this feature is new. Now they will be confused why emoji appeared under their message. + new to Discord users arent really familiar with reactions and that bots can interact with their messages, so this help message could be a good kick start for them.

**Comment by klendi** [comment]
Hi i am writing this comment because I wanna see the notification on discord. THNX BYE, KLENDI

**Comment by GlassToeStudio** [comment]
> I think adding a message to tell user "Hey click this emoji to auto format your code" could help a lot, especially as this feature is new. Now they will be confused why emoji appeared under their message. + new to Discord users arent really familiar with reactions and that bots can interact with their messages, so this help message could be a good kick start for them.

[8af9d40](https://github.com/bananaprotocol/confax/pull/33/commits/8af9d4037b81d3c315614172a7f8519c80f67c47) Should address this comment. Added automated message to prompt the user to react. Message will delete after a set amount of time - or when the user 'reacts'.

**Comment by bananaprotocol** [comment]
Thank you for the contribution! 👍

**Pull request merged**
