### PR TITLE
added banwords list

### PR DESCRIPTION
**Pull request by sietse85**
- feel free to adjust code-style

### CODE REVIEW

**Comment by GlassToeStudio** [comment]
<b>First up:</b> 
I do not think we will be banning users for using certain words. We do have a special role for members that could be handy in cases like this. Might want to consider adding a role to a warned member as opposed to an outright ban. That's not to say that we could do both; have a bad words list *and* and banned words list. Something to think about, but banning is not how we want to start. 

This PR is essentially a new module, yet there is an embedded command. While the command is a good touch, it should be its own file located int the commands folder.

The warned users are held in an array in memory - this will be lost if/when the bot goes down. We need a more permanent solution to warned user tracking.

Odd way of reading in a text file to get the list of banned words. The reading does work, though.

Once the text file is read, the resultant array has (on my machine) some artifacts that makes the banned word undetectable. As shown:
```
[ 'php\r', 'otherbannedword1\r', 'otherbannedword2' ]
```
"otherbannedword2" is detected while the 'php" and "otherbannedword1" are not. I'd suggest the use of a .json file to hold these banned words.

I consider this a bug, alternatives should be explored and the bug should be fixed.

# Other notes:
Not all users have their direct messages open. Would suggest checking before shooting them a DM.
```js
...
    if (lowercaseMessage.includes(bannedwords[word])) {
      message.channel.send(message.member.user + ' check your DM')
      message.author.send(
...
```
 * Inconsistencies in function naming. PascalCase mixed with camelCase
 * Naming and overall style does not strictly match the desired js 'standard' as noted in the ReadMe.
 * There are multiple unnecessary commits - and some non-standard commit naming conventions.
 * The formatting of the output of the embedded command needs work. See below:
 ```
 @GlassToe™ the banned words: php
 ,otherbannedword1
 ,otherbannedword2
```
Commas behind the word instead of in front of the previous word. Each word is a new line, so is a comma even necessary. This output could use an overhaul.

# Summary
Overall not a bad module. We have discussed a similar idea in the past and its good to see someone take up the challenge. while there are some things to address, I think this could turn into a great addition to Confax.

# Recommend:
 * Storing the banned word list on a .json and use a standardized way to pull in the data.
 * Squash these commits and follow a standard convention. 
 * Need a way to ensure warned users persists through bot crashes.
 * Fix naming conversation and adhere to js standard style.
 * Explore the option of adding a specific role to a user instead of banning them. The role should be readable from the config.json
 * Fix formatting of the command output.
 * Place the command code into its own file in the commands folder.

**Comment by sietse85** [comment]
I would also suggest adding Tags to this project

**Comment by bananaprotocol** [comment]
Thank you for the contribution, I'll quickly test it and probably merge!

**Comment by bananaprotocol** [comment]
Looks good, will merge!

**Pull request merged**
